In [1]:
import pandas as pd
import numpy as np

# 读取数据集
data = pd.read_csv('data/patient_data.csv')
data.head()

  PatientID  Age   BMI  BloodPressure  Cholesterol  DaysInHospital
0      P001   45  28.5            140          220              12
1      P002   32  22.1            120          190               5
2      P003   67  26.8            150          240               9
3      P004   28  19.7            110          180               3
4      P005   55  31.2            160          260              15

# 任务1：统计住院天数超过7天的患者数量及其占比

In [2]:
data['RiskLevel'] = np.where(data['DaysInHospital'] > 7,1,0)

In [3]:
data.head()

  PatientID  Age   BMI  BloodPressure  Cholesterol  DaysInHospital  RiskLevel
0      P001   45  28.5            140          220              12          1
1      P002   32  22.1            120          190               5          0
2      P003   67  26.8            150          240               9          1
3      P004   28  19.7            110          180               3          0
4      P005   55  31.2            160          260              15          1

In [4]:
riskCounts = data['RiskLevel'].value_counts()

In [5]:
print(riskCounts)

RiskLevel
1    16
0    14
Name: count, dtype: int64

In [6]:
print(riskCounts[0])

14

In [8]:
my_array = np.linspace(0, 10, 5)
print(my_array)

[ 0.   2.5  5.   7.5 10. ]

In [9]:
bmiArea = np.linspace(0,28,4)
print(bmiArea)

[ 0.          9.33333333 18.66666667 28.        ]

In [15]:
bmiArea = np.append(bmiArea,[np.inf])
print(bmiArea)

[ 0.          9.33333333 18.66666667 28.                 inf]

In [14]:
bmi_bins = np.array([0, 18.5, 24, 28, np.inf])
print(bmi_bins)

[ 0.  18.5 24.  28.   inf]

In [16]:
print(len(bmiArea))

5

In [22]:
bmi_labels = ['偏瘦', '正常', '超重', '肥胖']

data['bmiRange'] = pd.cut(data['BMI'],bins=bmiArea,labels=bmi_labels,right=False)
data.tail()

,PatientID,Age,BMI,BloodPressure,Cholesterol,DaysInHospital,RiskLevel,bmiRange
25,P026,30,18.9,112,172,3,0,超重
26,P027,57,30.7,159,250,15,1,肥胖
27,P028,48,23.8,129,192,6,0,超重
28,P029,71,28.2,151,232,11,1,肥胖
29,P030,34,21.5,118,178,4,0,超重

In [27]:
print(data.groupby('bmiRange')['RiskLevel'].apply(lambda x: (x==1).mean()))

bmiRange
偏瘦         NaN
正常    0.000000
超重    0.277778
肥胖    1.000000
Name: RiskLevel, dtype: float64

C:\Users\qgao2\AppData\Local\Temp\ipykernel_33108\2378349085.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(data.groupby('bmiRange')['RiskLevel'].apply(lambda x: (x==1).mean()))

In [28]:
print(data['bmiRange'].value_counts())

bmiRange
超重    18
肥胖    11
正常     1
偏瘦     0
Name: count, dtype: int64

In [29]:
a = np.linspace(0,100,5)
b = np.array(['小孩','青年','中年','老年'])
data['phase'] = pd.cut(data['Age'],bins=a,labels=b,right=False)
rate = data.groupby('phase')['RiskLevel'].apply(lambda x: (x == 1).mean())
num = data['phase'].value_counts()
print(rate,num)

phase
小孩         NaN
青年    0.222222
中年    1.000000
老年         NaN
Name: RiskLevel, dtype: float64 phase
青年    18
中年    12
小孩     0
老年     0
Name: count, dtype: int64

C:\Users\qgao2\AppData\Local\Temp\ipykernel_33108\324480779.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  rate = data.groupby('phase')['RiskLevel'].apply(lambda x: (x == 1).mean())